version: '3'
networks:
  inception:
    driver: bridge

services:
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: reverse_proxy
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: always

  db:
    container_name: db
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_NAME: ${MYSQL_NAME}
    image: db
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_NAME: ${MYSQL_NAME}
        WP_USER: ${WP_USER}
        WP_USER_PASSWORD: ${WP_USER_PWD}
        WP_USER_EMAIL: ${WP_USER_EMAIL}

    image: wordpress
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - wp_data:/var/www/html
    restart: always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ren-nasr/data/db/
      o: bind
  wp_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ren-nasr/data/wp/
      o: bind
