version: '3'
networks:
  inception:
    driver: bridge

services:
  reverse_proxy:
    container_name: reverse_proxy
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    image: reverse_proxy
    ports:
      - 443:443
    networks:
      - inception
    restart: always

  db:
    container_name: db
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_NAME: ${MYSQL_NAME}
    image: db
    env_file:
      - .env
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
      # - /home/ren-nasr/data/db/:/var/lib/mysql
    restart: always
  # wordpress:
  #   build: ./requirements/wordpress/
  #   networks:
  #     - inception

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/ren-nasr/data/db/
      o: bind
